language: python

matrix:
  include:

    - os: linux
      python: 3.6
      name: ubuntu 16.04 - python@3.6
      dist: xenial
      sudo: true
      env:
        - MATRIX_EVAL=""

    - os: linux
      python: 3.7
      name: ubuntu 16.04 - python@3.7
      dist: xenial
      sudo: true
      env:
        - MATRIX_EVAL=""

    - os: linux
      python: 3.8
      name: ubuntu 16.04 - python@3.8
      dist: xenial
      sudo: true
      env:
        - MATRIX_EVAL=""

    - os: linux
      python: 3.9
      name: ubuntu 16.04 - python@3.9
      dist: xenial
      sudo: true
      env:
        - MATRIX_EVAL=""
    
    - os: osx
      name: osx - python@3.8
      osx_image: xcode10.2
      language: shell 
      before_install:
        - brew install python@3.8
      env:
        - MATRIX_EVAL=""



before_install:
  - travis_retry eval "${MATRIX_EVAL}"
  - python -m pip install --upgrade pip
  - python -m pip --version
  - pip install -r requirements.txt

install:
  - python setup.py install

script:
  - python -m pytest --cov=MRIsegm --cov-config=.coveragerc

after_succes:
  - codecov