language: python

# ==== LINUX =====

os: linux
dist: xenial
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
jobs:
  include:
    # ======== OSX ========= 

    - name: 'OSX - Python 3.6 '
      os: osx
      language: shell
      before_install:
        - brew install python@3.6
        - python -m pip install --upgrade pip
        - python -m pip --version
        - pip install -r requirements.txt
      install:
        - python setup.py install
      script:
        - python -m pytest --cov=MRIsegm --cov-config=.coveragerc
      - name: 'OSX - Python 3.7 '
      os: osx
      language: shell
      before_install:
        - brew install python@3.7
        - python -m pip install --upgrade pip
        - python -m pip --version
        - pip install -r requirements.txt
      install:
        - python setup.py install
      script:
        - python -m pytest --cov=MRIsegm --cov-config=.coveragerc
      - name: 'OSX - Python 3.8 '
      os: osx
      language: shell
      before_install:
        - brew install python@3.8
        - python -m pip install --upgrade pip
        - python -m pip --version
        - pip install -r requirements.txt
      install:
        - python setup.py install
      script:
        - python -m pytest --cov=MRIsegm --cov-config=.coveragerc
      - name: 'OSX - Python 3.69'
      os: osx
      language: shell
      before_install:
        - brew install python@3.9
        - python -m pip install --upgrade pip
        - python -m pip --version
        - pip install -r requirements.txt
      install:
        - python setup.py install
      script:
        - python -m pytest --cov=MRIsegm --cov-config=.coveragerc


before_install:
  - python -m pip install --upgrade pip
  - python -m pip --version
  - pip install -r requirements.txt


install:
  - python setup.py install

script:
  - python -m pytest --cov=MRIsegm --cov-config=.coveragerc

after_succes:
  - codecov

notifications:
  email:

    recipients:
      - giuseppefilitto@gmail.com

    on_success: never
    on_failure: never