language: python

matrix:
  include:

    - os: linux
      python: 3.6
      name: ubuntu 16.04 - python@3.6
      dist: xenial
      sudo: true
      env:
        - MATRIX_EVAL=""

    - os: linux
      python: 3.7
      name: ubuntu 16.04 - python@3.7
      dist: xenial
      sudo: true
      env:
        - MATRIX_EVAL=""

    - os: linux
      python: 3.8
      name: ubuntu 16.04 - python@3.8
      dist: xenial
      sudo: true
      env:
        - MATRIX_EVAL=""

    - os: linux
      python: 3.9
      name: ubuntu 16.04 - python@3.9
      dist: xenial
      sudo: true
      env:
        - MATRIX_EVAL=""
    
    - os: osx
      name: "Python 3.8.0 on macOS 10.14"
      osx_image: xcode11.3
      language: shell
      env:
        - MATRIX_EVAL=""



before_install:
  - travis_retry eval "${MATRIX_EVAL}"
  - python3 -m pip install --upgrade pip
  - python3 -m pip --version
  - python3 -m pip install -r requirements.txt

install:
  - python3 setup.py install

script:
  - python3 -m pytest --cov=MRIsegm --cov-config=.coveragerc

after_succes:
  - codecov