language: python

matrix:
  include:

    - os: windows
      python: 3.9
      name: windows - python@3.9
      env:
        - MATRIX_EVAL=""

    - os: osx
      python: 3.9
      name: osx - python@3.9
      env:
        - MATRIX_EVAL=""
    
    - os: linux
      python: 3.9
      name: ubuntu 16.04 - python@3.9
      dist: xenial
      sudo: true
      env:
        - MATRIX_EVAL=""


before_install:
  - travis_retry eval "${MATRIX_EVAL}"
  - python3 -m pip install --upgrade pip
  - python3 -m pip --version
  - pip3 install -r requirements.txt

install:
  - python3 setup.py install

script:
  - travis_wait 45 python3 -m pytest --cov=MRIsegm --cov-config=.coveragerc

notifications:
  email:

    recipients:
      - giuseppefilitto@gmail.com

    on_success: never
    on_failure: never

after_succes:
  - codecov